<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice #{{ $order->invoice_code }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @media print {
            body {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }

            .no-print {
                display: none;
            }
        }
    </style>
</head>

<body class="bg-gray-100 p-8 print:p-0 print:bg-white">
    <div class="max-w-2xl mx-auto bg-white p-8 shadow-lg print:shadow-none print:w-full">
        <!-- Header -->
        <div class="flex justify-between items-start mb-8 border-b pb-4">
            <div>
                <h1 class="text-3xl font-bold text-orange-600">ReadyEat</h1>
                <p class="text-gray-600">Food Pre-Order System</p>
                <p class="text-sm text-gray-500 mt-1">Jl. Contoh No. 123, Jakarta</p>
            </div>
            <div class="text-right">
                <h2 class="text-xl font-bold text-gray-800">INVOICE</h2>
                <p class="text-gray-600">#{{ $order->invoice_code }}</p>
                <p class="text-sm text-gray-500 mt-1">Date:
                    {{ \Carbon\Carbon::parse($order->created_at)->format('d M Y H:i') }}</p>
            </div>
        </div>

        <!-- Customer Info -->
        <div class="mb-8">
            <h3 class="text-gray-600 uppercase text-xs font-bold mb-2">Bill To:</h3>
            <p class="font-bold text-lg">{{ $order->customer_name }}</p>
            <p class="text-gray-600">{{ $order->customer_phone }}</p>
            <p class="text-gray-600 mt-2">
                <span class="font-bold">Pickup Date:</span>
                {{ \Carbon\Carbon::parse($order->pickup_date)->format('l, d F Y') }}
            </p>
        </div>

        <!-- Order Items -->
        <table class="w-full mb-8">
            <thead>
                <tr class="border-b-2 border-gray-200">
                    <th class="text-left py-2">Item</th>
                    <th class="text-center py-2">Qty</th>
                    <th class="text-right py-2">Price</th>
                    <th class="text-right py-2">Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach($order->items as $item)
                    <tr class="border-b border-gray-100">
                        <td class="py-2">{{ $item->menu->name ?? 'Unknown Item' }}</td>
                        <td class="text-center py-2">{{ $item->quantity }}</td>
                        <td class="text-right py-2">Rp {{ number_format($item->price, 0, ',', '.') }}</td>
                        <td class="text-right py-2">Rp {{ number_format($item->price * $item->quantity, 0, ',', '.') }}</td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right py-4 font-bold">Total Amount:</td>
                    <td class="text-right py-4 font-bold text-xl">Rp
                        {{ number_format($order->total_price, 0, ',', '.') }}</td>
                </tr>
            </tfoot>
        </table>

        <!-- Footer -->
        <div class="border-t pt-4 text-center">
            <div class="mb-4">
                <span class="px-3 py-1 rounded-full text-sm font-bold 
                    {{ $order->status === 'payment_pending' ? 'bg-yellow-100 text-yellow-800' : '' }}
                    {{ $order->status === 'ready_for_pickup' ? 'bg-blue-100 text-blue-800' : '' }}
                    {{ $order->status === 'picked_up' ? 'bg-green-100 text-green-800' : '' }}
                    {{ $order->status === 'cancelled' ? 'bg-red-100 text-red-800' : '' }}">
                    STATUS: {{ strtoupper(str_replace('_', ' ', $order->status)) }}
                </span>
            </div>
            <p class="text-gray-500 text-sm">Thank you for your order!</p>
            <p class="text-gray-400 text-xs mt-2">Generated by ReadyEat System</p>
        </div>

        <!-- Print Button (Hidden when printing) -->
        <div class="mt-8 text-center no-print">
            <button onclick="window.print()"
                class="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 font-bold shadow-lg">
                Print Invoice
            </button>
            <button onclick="window.close()" class="ml-4 text-gray-600 hover:text-gray-800">
                Close
            </button>
        </div>
    </div>
    <script>
        // Auto print when opened
        window.onload = function () {
            // window.print();
        }
    </script>
</body>

</html>